# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d71a4085a62671948e01a613dd49fb584b0bc4734a80711a834ab95fde318e258e69efc909a4d6a27922cc867ec89c431de3d4b146a1be9be327a701ac2ae47

test:
  secret_key_base: abcc79042c8b779c92d3d12fc274a96c4932b089a8a2bff569304d226328e48294ecff539244db48a0aaaf2a65497ffd85956faffd1e82c5cef29a5a7d383cf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
